data_quality:
  rules:
    - name: "No Nulls"
      columns: ["customer_id", "gender"]
      rule: "not_null"
    - name: "Valid Gender"
      columns: ["gender"]
      rule: "in"
      values: ["Male", "Female"]

data_sources:
  api:
    users: "https://jsonplaceholder.typicode.com/users"
    posts: "https://jsonplaceholder.typicode.com/posts"
  csv:
    covid: "https://raw.githubusercontent.com/datasets/covid-19/main/data/time-series-19-covid-combined.csv"

storage:

  bronze_path: "data/bronze"
  local_path: "data/bronze"
  silver_path: "data/silver"
  gold_path: "data/gold"
  
  minio:
    endpoint: "minio:9000"
    access_key: "admin"
    secret_key: "password123"
    bronze_bucket: "bronze-layer"
    silver_bucket: "silver-layer"
    gold_bucket: "gold-layer"

database:
  host: "postgres"
  port: 5432
  database: "medallion_dw"
  user: "admin"
  password: "admin123"
  
  schemas:
    bronze: "bronze"
    silver: "silver"
    gold: "gold"


pipeline:
